### ISSUE TITLE
Please rename the master branch to the main branch.

### ISSUE THREAD

**Issue by rhatdan** [containers/libocispec#99]

**Comment by giuseppe** [comment]
done

**Comment by giuseppe** [comment]
related change: https://github.com/containers/libocispec/pull/100

**Comment by giuseppe** [comment]
fix for crun: https://github.com/containers/crun/pull/673

**Comment by flouthoc** [comment]
@rhatdan @giuseppe One small change in docs, `cargo` versions older then `0.51.0` alway fetches `master` instead of `default` branch when no branch is specified. We cant do much here so updating docs to specify `main` explicitly for old cargo versions in  following PR https://github.com/containers/libocispec/pull/101

For me it failed with error, fixed with specifying `main` explicity. 
```bash
Caused by:
  failed to load source for dependency `libocispec`

Caused by:
  Unable to update https://github.com/containers/libocispec

Caused by:
  failed to find branch `master`

Caused by:
  cannot locate remote-tracking branch 'origin/master'; class=Reference (4); code=NotFound (-3)
```
